version: "3"

services:
  microservicio1:
    build:
      context: ./back/CarbonFootprint
    environment:
      MONGO_URI: mongodb+srv://grupoWeb:grupoWeb@cluster0.syetq9a.mongodb.net/elRastro
      NODE_ENV: production
    ports:
      - "5005:5005"

  microservicio2:
    build:
      context: ./back/Cloudinary
    environment:
      MONGO_URI: mongodb+srv://grupoWeb:grupoWeb@cluster0.syetq9a.mongodb.net/elRastro
      NODE_ENV: production
    ports:
      - "5006:5006"

  microservicio3:
    build:
      context: ./back/Mensajes
    environment:
      MONGO_URI: mongodb+srv://grupoWeb:grupoWeb@cluster0.syetq9a.mongodb.net/elRastro
      NODE_ENV: production
    ports:
      - "5010:5010"

  microservicio4:
    build:
      context: ./back/OAuth
    environment:
      MONGO_URI: mongodb+srv://grupoWeb:grupoWeb@cluster0.syetq9a.mongodb.net/elRastro
      NODE_ENV: production
    ports:
      - "5009:5009"
  
  microservicio5:
    build:
      context: ./back/OpenStreetMap
    environment:
      MONGO_URI: mongodb+srv://grupoWeb:grupoWeb@cluster0.syetq9a.mongodb.net/elRastro
      NODE_ENV: production
    ports:
      - "5004:5004"
  
  microservicio6:
    build:
      context: ./back/Productos
    environment:
      MONGO_URI: mongodb+srv://grupoWeb:grupoWeb@cluster0.syetq9a.mongodb.net/elRastro
      NODE_ENV: production
    ports:
      - "5001:5001"
  
  microservicio7:
    build:
      context: ./back/Pujas
    environment:
      MONGO_URI: mongodb+srv://grupoWeb:grupoWeb@cluster0.syetq9a.mongodb.net/elRastro
      NODE_ENV: production
    ports:
      - "5003:5003"
  
  microservicio8:
    build:
      context: ./back/Usuarios
    environment:
      MONGO_URI: mongodb+srv://grupoWeb:grupoWeb@cluster0.syetq9a.mongodb.net/elRastro
      NODE_ENV: production
    ports:
      - "5002:5002"

  microservicio9:
    build:
      context: ./back/Valoraciones
    environment:
      MONGO_URI: mongodb+srv://grupoWeb:grupoWeb@cluster0.syetq9a.mongodb.net/elRastro
      NODE_ENV: production
    ports:
      - "5008:5008"

  frontend:
    build:
      context: ./front
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
