
POST http://localhost:5000/pujas/ HTTP/1.1
Content-Type: application/json

{
  "comprador": "Juan Pérez",
  "producto": "ObjectId('652ece23cd459c79ed51b88f')",  // Reemplaza con el ID del producto real
  "precio": 100.00
  }

