// get all pujas
# GET   http://localhost:5000/pujas HTTP/1.1
# Content-Type: application/json

// crear una puja
 POST  http://localhost:5000/pujas HTTP/1.1
 Content-Type: application/json

 {
     "producto": "654ccee9cd48927b0fbd3a9d",
     "comprador": "653e4c42646ba4c6ea2eff33",
     "precio": 200
 }

//get pujas 