//Get de todos los productos
# GET   http://localhost:5001/productos/
# Content-Type: application/json

//Post de un producto
# POST  http://localhost:5001/productos/ HTTP/1.1
# Content-Type: application/json

# {
#   "vendedor" : "653e4c42646ba4c6ea2eff33",
#   "descripcion" : "Producto 1",
#   "precioInicial" : 100,
#   "precioActual" : 100,
#   "categorias" : "Juegos, Electronica",
#   "nombre" : "Producto 1"
# }

//Eliminar producto por ID
# DELETE http://localhost:5001/productos/654cd30ac813f182b077ff31 HTTP/1.1

//Get de productos por id
# GET   http://localhost:5001/productos/654ccf26cd48927b0fbd3aa0 HTTP/1.1

//Get de productos ofertados por un vendedor
# GET  http://localhost:5001/productos/productos-ofertados/654cccc214895f1cfc1192f2 HTTP/1.1

//Get de productos por categoria
#GET  http://localhost:5001/productos/productos-categoria/Juegos HTTP/1.1

# //Editar con PUT de un producto con ID especifico
# PUT   http://localhost:5001/productos/654cce4acd48927b0fbd3a91 HTTP/1.1
# Content-Type: application/json

# {
#   "vendedor" : "653e4c42646ba4c6ea2eff33",
#   "descripcion" : "Producto 1EDITADO",
#   "precioInicial" : 200,
#   "precioActual" : 200,
#   "categorias" : "Juegos, Electronica, Editado",
#   "nombre" : "Producto 1 Editado"
# }

//Get de productos por nombre
# GET  http://localhost:5001/productos/productos-usuario/C HTTP/1.1

//get de productos ordenados por cantidad de pujas
GET  http://localhost:5001/productos/productos-ordenados-por-pujas/Juegos HTTP/1.1